# ===== H2 en mémoire (par défaut, kaykhdem direct) =====
hibernate.connection.driver_class=org.h2.Driver
hibernate.connection.url=jdbc:h2:mem:stockdb;DB_CLOSE_DELAY=-1
hibernate.connection.username=sa
hibernate.connection.password=
hibernate.dialect=org.hibernate.dialect.H2Dialect

# ===== MySQL (7ayyed # w bddel li fo9 ila bghiti) =====
#hibernate.connection.driver_class=com.mysql.cj.jdbc.Driver
#hibernate.connection.url=jdbc:mysql://localhost:3306/stock?createDatabaseIfNotExist=true
#hibernate.connection.username=root
#hibernate.connection.password=
#hibernate.dialect=org.hibernate.dialect.MySQL8Dialect

# create-drop = les tables kaytcreaw w kaytms7o mnin tssali
hibernate.hbm2ddl.auto=create-drop
hibernate.show_sql=false
hibernate.format_sql=true
